### ISSUE TITLE
Possible to use transformers?

### ISSUE THREAD

**Issue by wstrange** [google/built_json.dart#13]
Is it possible to use a transformer rather than mix the value class and the generated class in the same directory?  The current example looks a little cumbersome. 

(I dont fully understand how it works - so if this not possible please ignore :-) )

**Comment by davidmorgan** [comment]
Good question.

The big advantage of source_gen over transformers is interoperation with other tools. In particular, the analyzer and your IDE can find all the code, and stack traces are meaningful.

This is a response to issues with transformers being too "black box"; they're opaque to most tools.

source_gen is very much "white box" :) ... and the idea is that, while this is a little ugly, it should lead to a better development experience overall.

It might, though, be nice to put the generated files in an alternative folder. I expect this will arrive as an option at some point.

So, I certainly agree with "a little cumbersome". Hopefully this is a reasonable trade-off!

**Comment by wstrange** [comment]
Fair nuff! Thanks for the explanation, I'll close the issue.
