### ISSUE TITLE
the package is not compatible with quiver 0.22.0

### ISSUE THREAD

**Issue by zoechi** [google/built_json.dart#33]
```
 quiver: '>=0.21.0 <0.22.0'
```

**Comment by davidmorgan** [comment]
Should just be a matter of bumping the versions. I'll take a look tomorrow. Thanks for filing!

**Comment by davidmorgan** [comment]
Now fixed, please re-open if you have any problems. Thanks!

**Comment by zoechi** [comment]
Great, thanks!

A question. I tried your packages in one of my projects where I use an `.analysis_options` file with strong mode and most linter rules enabled. The generated code causes quite a lot of hints and warnings.

`.analysis_options` provides an option to exclude files but that doesn't yet work properly.

Do you plan to support strong mode (actually not tested if strong mode alone causes hints/warnings) and perhaps other linter rules?

**Comment by davidmorgan** [comment]
Yes, we will definitely support strong mode. Could you file an issue with example hints/warnings please?

**Comment by zoechi** [comment]
I saw you took the first steps already. When I find time to try it again and run into issues, I'll create a concrete issue. Thanks for your great work :)
